### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jlukic** [the-simian/gulp-concat-filenames#7]
Hi, just want to make sure no breaking changes were in `1.0`

Couldnt find a changelog or release notes.

**Comment by the-simian** [comment]
Nothing broke, its just a stable release, and no longer in alpha.

The semver update was here: https://github.com/the-simian/gulp-concat-filenames/commit/0854edfffa6250a0a74f043f0bc4370d14ab5959

**Comment by jlukic** [comment]
Thanks for the response, and the package.

**Comment by the-simian** [comment]
@jlukic no problem. Don't hesitate to make an issue if there's some functionality you think would be reasonable to be in this package.
